// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5U4Z1-NgoC13AVeT3vdfdvpZIutNxJmI',
    appId: '1:916806684305:web:2681932480da156a4ab930',
    messagingSenderId: '916806684305',
    projectId: 'nerd-collector',
    authDomain: 'nerd-collector.firebaseapp.com',
    storageBucket: 'nerd-collector.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIH9DLRfrYqztMb6K0cqxwoQiYa76Ny7c',
    appId: '1:916806684305:android:3cdd95e13f82d72e4ab930',
    messagingSenderId: '916806684305',
    projectId: 'nerd-collector',
    storageBucket: 'nerd-collector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXDCO50zVHYPPi8gRom5VJFfUtoUW6mM',
    appId: '1:916806684305:ios:796ed7563820ad924ab930',
    messagingSenderId: '916806684305',
    projectId: 'nerd-collector',
    storageBucket: 'nerd-collector.appspot.com',
    iosClientId: '916806684305-nclogft02uduam8nv3ba4q3rb051cfnp.apps.googleusercontent.com',
    iosBundleId: 'com.nerdcollector.nerdcollector',
  );
}
